% (C) Copyright 2023 DQ Robotics Developers
% This file is part of DQ Robotics.
%
%     DQ Robotics is free software: you can redistribute it and/or modify
%     it under the terms of the GNU Lesser General Public License as published 
%     by the Free Software Foundation, either version 3 of the License, or
%     (at your option) any later version.
%
%     DQ Robotics is distributed in the hope that it will be useful,
%     but WITHOUT ANY WARRANTY; without even the implied warranty of
%     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
%     GNU Lesser General Public License for more details.
%
%     You should have received a copy of the GNU Lesser General Public License
%     along with DQ Robotics.  If not, see <http://www.gnu.org/licenses/>.
%
% DQ Robotics website: dqrobotics.github.io
%
% Contributors to this file:
%     Juan Jose Quiroz Omana (juanjqo@g.ecc.u-tokyo.ac.jp)

function show_joint_velocities(reference, measurement)
  %% This function plots the control inputs generated by the controller
  %% and the measured joint velocities.
    h1 = figure;
    set(h1, 'DefaultTextFontSize', 10);
    set(h1, 'DefaultAxesFontSize', 10); % [pt]
    set(h1, 'DefaultAxesFontName', 'mwa_cmr10');
    set(h1, 'DefaultTextFontName', 'mwa_cmr10');
    set(h1, 'Units', 'centimeters');
    pos = get(h1, 'Position');
    pos(3) = 20; % Select the width of the figure in [cm] 17
    pos(4) = 10; % Select the height of the figure in [cm] 6
    set(h1, 'Position', pos);
    set(h1, 'PaperType', 'a4letter');
    set(h1,'PaperPositionMode','auto')
    a = 2;
    b = 4;
    w = 4;
    fontsize = 10;
    for i=1:7
    subplot(a,b,i);
    plot(reference(i,:),'b', 'LineWidth',w);
    hold on
    plot(measurement(i,:),':r', 'LineWidth',3);
    axis([0 inf -0.1 0.1])
    set(gca, 'FontSize', fontsize );
    fig = gcf;
    fig.Color = [1 1 1];
    box('off');
    title('$\dot{q}$', 'Interpreter','latex', 'Rotation', 0)
    end
    legend('reference', 'measurement')
end

